### ISSUE TITLE
Refactor Entity-Hostile structure

### ISSUE THREAD

**Issue by lagebr** [lagebr/blob_game#2]
This will make the code more clean and easier to work with.

**Comment by lagebr** [comment]
* We (@isaacarvestad & @lagebr) need to make Hostile and Entity abstract.
* Remove WithTarget
* Move all createPhysicsBody into one method.

**Comment by lagebr** [comment]
* Now all hostiles use methods within PhysicsHelper
* We've removed the `HostileWithTarget`

**Comment by isaacarvestad** [comment]
Since each `Entity` physics body varies we could consider moving the physics body creation into each respective `Entity` sub-class. `PhysicsHelper` could still provide helper methods for quickly creating parts of a physics body, such as a fixture definition. 

This isn't really a problem right now but if we multiply the number of `Entity` types with three, `PhysicsHelper` will quickly become bloated with large amounts of "createDynamic[Circle, Square, SquareLight, etc.]Body" methods.
